package view;

//import panelView.*;
import java.awt.Color;
import javax.swing.JComponent;

public class MainViewForm extends javax.swing.JFrame {
    private int selectedIndex = -1;

    public MainViewForm(){
        initComponents();
        recolorDefaultSwitchPanel();
    }

    private void setForm(JComponent com){
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    } 

    private void recolorDefaultSwitchPanel(){
        repaint();
        dashboardPanel.setBackground(new Color(124, 147, 195));
        hewanPanel.setBackground(new Color(124, 147, 195));
        produkPanel.setBackground(new Color(124, 147, 195));
        groomingPanel.setBackground(new Color(124, 147, 195));
        transaksiPanel.setBackground(new Color(124, 147, 195));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        navBarPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoIconLabel = new javax.swing.JLabel();
        petshopLabel = new javax.swing.JLabel();
        petshopLabel2 = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        jpanelRoundCustomer = new costum.JpanelRound();
        customerIconLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        hewanPanel = new javax.swing.JPanel();
        jpanelRoundHewan = new costum.JpanelRound();
        hewanIconLabel = new javax.swing.JLabel();
        hewanLabel = new javax.swing.JLabel();
        produkPanel = new javax.swing.JPanel();
        jpanelRoundProduk = new costum.JpanelRound();
        produkIconLabel = new javax.swing.JLabel();
        produkLabel = new javax.swing.JLabel();
        groomingPanel = new javax.swing.JPanel();
        jpanelRoundGrooming = new costum.JpanelRound();
        groomingIconLabel = new javax.swing.JLabel();
        groomingLabel = new javax.swing.JLabel();
        adopsiPanel = new javax.swing.JPanel();
        jpanelRoundAdopsi = new costum.JpanelRound();
        adopsiIconLabel = new javax.swing.JLabel();
        adopsiLabel = new javax.swing.JLabel();
        penitipanPanel = new javax.swing.JPanel();
        jpanelRoundPenitipan = new costum.JpanelRound();
        penitipanIconLabel = new javax.swing.JLabel();
        penitipanLabel = new javax.swing.JLabel();
        detailPenjualanPanel = new javax.swing.JPanel();
        jpanelRoundDetailPenjualan = new costum.JpanelRound();
        detailPenjualanIconLabel = new javax.swing.JLabel();
        detailPenjualanLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(1360, 757));

        navBarPanel.setBackground(new java.awt.Color(124, 147, 195));
        navBarPanel.setPreferredSize(new java.awt.Dimension(970, 0));

        logoPanel.setBackground(new java.awt.Color(124, 147, 195));

        logoIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoPetshop.png"))); // NOI18N
        logoIconLabel.setText("jLabel4");

        petshopLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        petshopLabel.setForeground(new java.awt.Color(255, 255, 255));
        petshopLabel.setText("PETSHOP");

        petshopLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        petshopLabel2.setForeground(new java.awt.Color(255, 255, 255));
        petshopLabel2.setText("MANAGEMENT SYSTEM");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(petshopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(petshopLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(petshopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(petshopLabel2)))
                .addGap(28, 28, 28))
        );

        customerPanel.setBackground(new java.awt.Color(124, 147, 195));
        customerPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundCustomer.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundCustomer.setRoundBottomLeft(20);
        jpanelRoundCustomer.setRoundBottomRight(20);
        jpanelRoundCustomer.setRoundTopLeft(20);
        jpanelRoundCustomer.setRoundTopRight(20);

        customerIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N

        customerLabel.setBackground(new java.awt.Color(0, 0, 0));
        customerLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLabel.setText("Customer");

        javax.swing.GroupLayout jpanelRoundCustomerLayout = new javax.swing.GroupLayout(jpanelRoundCustomer);
        jpanelRoundCustomer.setLayout(jpanelRoundCustomerLayout);
        jpanelRoundCustomerLayout.setHorizontalGroup(
            jpanelRoundCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(customerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundCustomerLayout.setVerticalGroup(
            jpanelRoundCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        hewanPanel.setBackground(new java.awt.Color(124, 147, 195));
        hewanPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundHewan.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundHewan.setRoundBottomLeft(20);
        jpanelRoundHewan.setRoundBottomRight(20);
        jpanelRoundHewan.setRoundTopLeft(20);
        jpanelRoundHewan.setRoundTopRight(20);

        hewanIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hewanIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hewan.png"))); // NOI18N

        hewanLabel.setBackground(new java.awt.Color(0, 0, 0));
        hewanLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hewanLabel.setForeground(new java.awt.Color(255, 255, 255));
        hewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hewanLabel.setText("Hewan");

        javax.swing.GroupLayout jpanelRoundHewanLayout = new javax.swing.GroupLayout(jpanelRoundHewan);
        jpanelRoundHewan.setLayout(jpanelRoundHewanLayout);
        jpanelRoundHewanLayout.setHorizontalGroup(
            jpanelRoundHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hewanIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hewanLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundHewanLayout.setVerticalGroup(
            jpanelRoundHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hewanIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hewanLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout hewanPanelLayout = new javax.swing.GroupLayout(hewanPanel);
        hewanPanel.setLayout(hewanPanelLayout);
        hewanPanelLayout.setHorizontalGroup(
            hewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        hewanPanelLayout.setVerticalGroup(
            hewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        produkPanel.setBackground(new java.awt.Color(124, 147, 195));
        produkPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundProduk.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundProduk.setRoundBottomLeft(20);
        jpanelRoundProduk.setRoundBottomRight(20);
        jpanelRoundProduk.setRoundTopLeft(20);
        jpanelRoundProduk.setRoundTopRight(20);

        produkIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/produk.png"))); // NOI18N

        produkLabel.setBackground(new java.awt.Color(0, 0, 0));
        produkLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        produkLabel.setForeground(new java.awt.Color(255, 255, 255));
        produkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produkLabel.setText("Produk");

        javax.swing.GroupLayout jpanelRoundProdukLayout = new javax.swing.GroupLayout(jpanelRoundProduk);
        jpanelRoundProduk.setLayout(jpanelRoundProdukLayout);
        jpanelRoundProdukLayout.setHorizontalGroup(
            jpanelRoundProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produkIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(produkLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundProdukLayout.setVerticalGroup(
            jpanelRoundProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produkIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(produkLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout produkPanelLayout = new javax.swing.GroupLayout(produkPanel);
        produkPanel.setLayout(produkPanelLayout);
        produkPanelLayout.setHorizontalGroup(
            produkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        produkPanelLayout.setVerticalGroup(
            produkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        groomingPanel.setBackground(new java.awt.Color(124, 147, 195));
        groomingPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundGrooming.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundGrooming.setRoundBottomLeft(20);
        jpanelRoundGrooming.setRoundBottomRight(20);
        jpanelRoundGrooming.setRoundTopLeft(20);
        jpanelRoundGrooming.setRoundTopRight(20);

        groomingIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groomingIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grooming.png"))); // NOI18N

        groomingLabel.setBackground(new java.awt.Color(0, 0, 0));
        groomingLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        groomingLabel.setForeground(new java.awt.Color(255, 255, 255));
        groomingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groomingLabel.setText("Grooming");

        javax.swing.GroupLayout jpanelRoundGroomingLayout = new javax.swing.GroupLayout(jpanelRoundGrooming);
        jpanelRoundGrooming.setLayout(jpanelRoundGroomingLayout);
        jpanelRoundGroomingLayout.setHorizontalGroup(
            jpanelRoundGroomingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundGroomingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groomingIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(groomingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundGroomingLayout.setVerticalGroup(
            jpanelRoundGroomingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundGroomingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groomingIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groomingLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout groomingPanelLayout = new javax.swing.GroupLayout(groomingPanel);
        groomingPanel.setLayout(groomingPanelLayout);
        groomingPanelLayout.setHorizontalGroup(
            groomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groomingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundGrooming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        groomingPanelLayout.setVerticalGroup(
            groomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groomingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundGrooming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        adopsiPanel.setBackground(new java.awt.Color(124, 147, 195));
        adopsiPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundAdopsi.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundAdopsi.setRoundBottomLeft(20);
        jpanelRoundAdopsi.setRoundBottomRight(20);
        jpanelRoundAdopsi.setRoundTopLeft(20);
        jpanelRoundAdopsi.setRoundTopRight(20);

        adopsiIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adopsiIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/adopsi.png"))); // NOI18N

        adopsiLabel.setBackground(new java.awt.Color(0, 0, 0));
        adopsiLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adopsiLabel.setForeground(new java.awt.Color(255, 255, 255));
        adopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adopsiLabel.setText("Adopsi");

        javax.swing.GroupLayout jpanelRoundAdopsiLayout = new javax.swing.GroupLayout(jpanelRoundAdopsi);
        jpanelRoundAdopsi.setLayout(jpanelRoundAdopsiLayout);
        jpanelRoundAdopsiLayout.setHorizontalGroup(
            jpanelRoundAdopsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundAdopsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adopsiIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(adopsiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundAdopsiLayout.setVerticalGroup(
            jpanelRoundAdopsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundAdopsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adopsiIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adopsiLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout adopsiPanelLayout = new javax.swing.GroupLayout(adopsiPanel);
        adopsiPanel.setLayout(adopsiPanelLayout);
        adopsiPanelLayout.setHorizontalGroup(
            adopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundAdopsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        adopsiPanelLayout.setVerticalGroup(
            adopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundAdopsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        penitipanPanel.setBackground(new java.awt.Color(124, 147, 195));
        penitipanPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundPenitipan.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundPenitipan.setRoundBottomLeft(20);
        jpanelRoundPenitipan.setRoundBottomRight(20);
        jpanelRoundPenitipan.setRoundTopLeft(20);
        jpanelRoundPenitipan.setRoundTopRight(20);

        penitipanIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penitipanIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penitipan.png"))); // NOI18N

        penitipanLabel.setBackground(new java.awt.Color(0, 0, 0));
        penitipanLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        penitipanLabel.setForeground(new java.awt.Color(255, 255, 255));
        penitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penitipanLabel.setText("Penitipan");

        javax.swing.GroupLayout jpanelRoundPenitipanLayout = new javax.swing.GroupLayout(jpanelRoundPenitipan);
        jpanelRoundPenitipan.setLayout(jpanelRoundPenitipanLayout);
        jpanelRoundPenitipanLayout.setHorizontalGroup(
            jpanelRoundPenitipanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundPenitipanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penitipanIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(penitipanLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelRoundPenitipanLayout.setVerticalGroup(
            jpanelRoundPenitipanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundPenitipanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penitipanIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penitipanLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout penitipanPanelLayout = new javax.swing.GroupLayout(penitipanPanel);
        penitipanPanel.setLayout(penitipanPanelLayout);
        penitipanPanelLayout.setHorizontalGroup(
            penitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundPenitipan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        penitipanPanelLayout.setVerticalGroup(
            penitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundPenitipan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        detailPenjualanPanel.setBackground(new java.awt.Color(124, 147, 195));
        detailPenjualanPanel.setPreferredSize(new java.awt.Dimension(105, 107));

        jpanelRoundDetailPenjualan.setBackground(new java.awt.Color(190, 205, 238));
        jpanelRoundDetailPenjualan.setRoundBottomLeft(20);
        jpanelRoundDetailPenjualan.setRoundBottomRight(20);
        jpanelRoundDetailPenjualan.setRoundTopLeft(20);
        jpanelRoundDetailPenjualan.setRoundTopRight(20);

        detailPenjualanIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailPenjualanIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detailPenjualan.png"))); // NOI18N

        detailPenjualanLabel.setBackground(new java.awt.Color(0, 0, 0));
        detailPenjualanLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        detailPenjualanLabel.setForeground(new java.awt.Color(255, 255, 255));
        detailPenjualanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailPenjualanLabel.setText("Detail Penjualan");

        javax.swing.GroupLayout jpanelRoundDetailPenjualanLayout = new javax.swing.GroupLayout(jpanelRoundDetailPenjualan);
        jpanelRoundDetailPenjualan.setLayout(jpanelRoundDetailPenjualanLayout);
        jpanelRoundDetailPenjualanLayout.setHorizontalGroup(
            jpanelRoundDetailPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundDetailPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailPenjualanIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(detailPenjualanLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        jpanelRoundDetailPenjualanLayout.setVerticalGroup(
            jpanelRoundDetailPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRoundDetailPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailPenjualanIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailPenjualanLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout detailPenjualanPanelLayout = new javax.swing.GroupLayout(detailPenjualanPanel);
        detailPenjualanPanel.setLayout(detailPenjualanPanelLayout);
        detailPenjualanPanelLayout.setHorizontalGroup(
            detailPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPenjualanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundDetailPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        detailPenjualanPanelLayout.setVerticalGroup(
            detailPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPenjualanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRoundDetailPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout navBarPanelLayout = new javax.swing.GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(produkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groomingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(penitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailPenjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        navBarPanelLayout.setVerticalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailPenjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groomingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setOpaque(false);
        contentPanel.setPreferredSize(new java.awt.Dimension(1356, 644));
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adopsiIconLabel;
    private javax.swing.JLabel adopsiLabel;
    private javax.swing.JPanel adopsiPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel customerIconLabel;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel detailPenjualanIconLabel;
    private javax.swing.JLabel detailPenjualanLabel;
    private javax.swing.JPanel detailPenjualanPanel;
    private javax.swing.JLabel groomingIconLabel;
    private javax.swing.JLabel groomingLabel;
    private javax.swing.JPanel groomingPanel;
    private javax.swing.JLabel hewanIconLabel;
    private javax.swing.JLabel hewanLabel;
    private javax.swing.JPanel hewanPanel;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private costum.JpanelRound jpanelRoundAdopsi;
    private costum.JpanelRound jpanelRoundCustomer;
    private costum.JpanelRound jpanelRoundDetailPenjualan;
    private costum.JpanelRound jpanelRoundGrooming;
    private costum.JpanelRound jpanelRoundHewan;
    private costum.JpanelRound jpanelRoundPenitipan;
    private costum.JpanelRound jpanelRoundProduk;
    private javax.swing.JLabel logoIconLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JLabel penitipanIconLabel;
    private javax.swing.JLabel penitipanLabel;
    private javax.swing.JPanel penitipanPanel;
    private javax.swing.JLabel petshopLabel;
    private javax.swing.JLabel petshopLabel2;
    private javax.swing.JLabel produkIconLabel;
    private javax.swing.JLabel produkLabel;
    private javax.swing.JPanel produkPanel;
    // End of variables declaration//GEN-END:variables
}
