package panelView;

public class AdopsiMainPanel extends javax.swing.JPanel {
    

    public AdopsiMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchAdopsiInputPanel = new javax.swing.JPanel();
        searchAdopsiInputLabel = new javax.swing.JLabel();
        searchAdopsiInputTextField = new javax.swing.JTextField();
        searchAdopsiInputButton = new javax.swing.JButton();
        adopsiFormPanel = new javax.swing.JPanel();
        idAdopsiPanel = new javax.swing.JPanel();
        idAdopsiLabel = new javax.swing.JLabel();
        idAdopsiTextField = new javax.swing.JTextField();
        namaAdopterPanel = new javax.swing.JPanel();
        namaAdopterLabel = new javax.swing.JLabel();
        namaAdopterTextField = new javax.swing.JTextField();
        noTeleponPanel = new javax.swing.JPanel();
        noTeleponLabel = new javax.swing.JLabel();
        noTeleponTextField = new javax.swing.JTextField();
        namaHewanPanel = new javax.swing.JPanel();
        namaHewanLabel = new javax.swing.JLabel();
        namaHewanDropdown = new javax.swing.JComboBox<>();
        tanggalAdopsiPanel = new javax.swing.JPanel();
        tanggalAdopsiLabel = new javax.swing.JLabel();
        tanggalAdopsiDateChooser = new com.toedter.calendar.JDateChooser();
        statusAdopsiPanel = new javax.swing.JPanel();
        statusAdopsiLabel = new javax.swing.JLabel();
        statusAdopsiDropdown = new javax.swing.JComboBox<>();
        biayaAdopsiPanel = new javax.swing.JPanel();
        biayaAdopsiLabel = new javax.swing.JLabel();
        biayaAdopsiTextField = new javax.swing.JTextField();
        alamatAdopterPanel = new javax.swing.JPanel();
        alamatAdopterLabel = new javax.swing.JLabel();
        alamatAdopterScrollPane = new javax.swing.JScrollPane();
        deskripsiProdukTextArea = new javax.swing.JTextArea();
        gamabarAdoptMeLabel = new javax.swing.JLabel();
        simpanAdopsiButton = new javax.swing.JButton();
        batalAdopsiButton = new javax.swing.JButton();
        headerAdopsiPanel = new javax.swing.JPanel();
        headerAdopsiLabel = new javax.swing.JLabel();
        headergambarAdopsiLabel = new javax.swing.JLabel();
        adopsiButtonPanel = new javax.swing.JPanel();
        barukanAdopsiButton = new javax.swing.JButton();
        hapusAdopsiButton = new javax.swing.JButton();
        tambahAdopsiButton = new javax.swing.JButton();
        dataAdopsiPanel = new javax.swing.JPanel();
        dataAdopsiScrollPane = new javax.swing.JScrollPane();
        tableAdopsi = new javax.swing.JTable();
        dataAdopsiLabel = new javax.swing.JLabel();
        tyAdopsiPanel = new javax.swing.JPanel();
        tyAdopsiLabel = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1356, 644));

        searchAdopsiInputPanel.setBackground(new java.awt.Color(238, 242, 250));
        searchAdopsiInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchAdopsiInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        searchAdopsiInputLabel.setText("Pencarian Adopsi");

        searchAdopsiInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdopsiInputTextFieldActionPerformed(evt);
            }
        });
        searchAdopsiInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchAdopsiInputTextFieldKeyPressed(evt);
            }
        });

        searchAdopsiInputButton.setBackground(new java.awt.Color(102, 126, 190));
        searchAdopsiInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchAdopsiInputButton.setText("Cari");
        searchAdopsiInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdopsiInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchAdopsiInputPanelLayout = new javax.swing.GroupLayout(searchAdopsiInputPanel);
        searchAdopsiInputPanel.setLayout(searchAdopsiInputPanelLayout);
        searchAdopsiInputPanelLayout.setHorizontalGroup(
            searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAdopsiInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                        .addComponent(searchAdopsiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(searchAdopsiInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchAdopsiInputPanelLayout.setVerticalGroup(
            searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                .addComponent(searchAdopsiInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAdopsiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAdopsiInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        adopsiFormPanel.setBackground(new java.awt.Color(238, 242, 250));

        idAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        idAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idAdopsiLabel.setText("ID Adopsi");

        idAdopsiTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idAdopsiPanelLayout = new javax.swing.GroupLayout(idAdopsiPanel);
        idAdopsiPanel.setLayout(idAdopsiPanelLayout);
        idAdopsiPanelLayout.setHorizontalGroup(
            idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(idAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(idAdopsiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        idAdopsiPanelLayout.setVerticalGroup(
            idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAdopsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaAdopterPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaAdopterPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaAdopterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaAdopterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaAdopterLabel.setText("Nama Adopter");

        namaAdopterTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaAdopterTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout namaAdopterPanelLayout = new javax.swing.GroupLayout(namaAdopterPanel);
        namaAdopterPanel.setLayout(namaAdopterPanelLayout);
        namaAdopterPanelLayout.setHorizontalGroup(
            namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaAdopterPanelLayout.createSequentialGroup()
                        .addComponent(namaAdopterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(namaAdopterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaAdopterPanelLayout.setVerticalGroup(
            namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaAdopterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAdopterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponPanel.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        noTeleponLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noTeleponLabel.setText("No Telepon");

        noTeleponTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout noTeleponPanelLayout = new javax.swing.GroupLayout(noTeleponPanel);
        noTeleponPanel.setLayout(noTeleponPanelLayout);
        noTeleponPanelLayout.setHorizontalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noTeleponPanelLayout.createSequentialGroup()
                        .addComponent(noTeleponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        noTeleponPanelLayout.setVerticalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        namaHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaHewanLabel.setText("Nama Hewan");

        namaHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        namaHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaHewanPanelLayout = new javax.swing.GroupLayout(namaHewanPanel);
        namaHewanPanel.setLayout(namaHewanPanelLayout);
        namaHewanPanelLayout.setHorizontalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaHewanPanelLayout.createSequentialGroup()
                        .addComponent(namaHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(namaHewanDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaHewanPanelLayout.setVerticalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tanggalAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        tanggalAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        tanggalAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalAdopsiLabel.setText("Tanggal Adopsi");

        javax.swing.GroupLayout tanggalAdopsiPanelLayout = new javax.swing.GroupLayout(tanggalAdopsiPanel);
        tanggalAdopsiPanel.setLayout(tanggalAdopsiPanelLayout);
        tanggalAdopsiPanelLayout.setHorizontalGroup(
            tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tanggalAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(tanggalAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(tanggalAdopsiDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tanggalAdopsiPanelLayout.setVerticalGroup(
            tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalAdopsiDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        statusAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        statusAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        statusAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAdopsiLabel.setText("Status Adopsi");

        statusAdopsiDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusAdopsiDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        statusAdopsiDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusAdopsiDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusAdopsiPanelLayout = new javax.swing.GroupLayout(statusAdopsiPanel);
        statusAdopsiPanel.setLayout(statusAdopsiPanelLayout);
        statusAdopsiPanelLayout.setHorizontalGroup(
            statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(statusAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(statusAdopsiDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusAdopsiPanelLayout.setVerticalGroup(
            statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAdopsiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        biayaAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        biayaAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        biayaAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        biayaAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        biayaAdopsiLabel.setText("Biaya Adopsi");

        biayaAdopsiTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout biayaAdopsiPanelLayout = new javax.swing.GroupLayout(biayaAdopsiPanel);
        biayaAdopsiPanel.setLayout(biayaAdopsiPanelLayout);
        biayaAdopsiPanelLayout.setHorizontalGroup(
            biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biayaAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biayaAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(biayaAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(biayaAdopsiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        biayaAdopsiPanelLayout.setVerticalGroup(
            biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biayaAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biayaAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaAdopsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alamatAdopterPanel.setBackground(new java.awt.Color(255, 255, 255));
        alamatAdopterPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        alamatAdopterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatAdopterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alamatAdopterLabel.setText("Alamat");

        deskripsiProdukTextArea.setColumns(20);
        deskripsiProdukTextArea.setRows(5);
        alamatAdopterScrollPane.setViewportView(deskripsiProdukTextArea);

        javax.swing.GroupLayout alamatAdopterPanelLayout = new javax.swing.GroupLayout(alamatAdopterPanel);
        alamatAdopterPanel.setLayout(alamatAdopterPanelLayout);
        alamatAdopterPanelLayout.setHorizontalGroup(
            alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatAdopterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatAdopterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alamatAdopterPanelLayout.setVerticalGroup(
            alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatAdopterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatAdopterScrollPane)
                .addContainerGap())
        );

        gamabarAdoptMeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/adoption.png"))); // NOI18N

        javax.swing.GroupLayout adopsiFormPanelLayout = new javax.swing.GroupLayout(adopsiFormPanel);
        adopsiFormPanel.setLayout(adopsiFormPanelLayout);
        adopsiFormPanelLayout.setHorizontalGroup(
            adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addComponent(idAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaAdopterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biayaAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatAdopterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(gamabarAdoptMeLabel)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        adopsiFormPanelLayout.setVerticalGroup(
            adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatAdopterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaAdopterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))))
            .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(gamabarAdoptMeLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        simpanAdopsiButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanAdopsiButton.setText("Simpan");
        simpanAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanAdopsiButtonActionPerformed(evt);
            }
        });

        batalAdopsiButton.setBackground(new java.awt.Color(237, 8, 0));
        batalAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        batalAdopsiButton.setText("Batalkan");
        batalAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalAdopsiButtonActionPerformed(evt);
            }
        });

        headerAdopsiPanel.setBackground(new java.awt.Color(124, 147, 195));

        headerAdopsiLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        headerAdopsiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paw.png"))); // NOI18N
        headerAdopsiLabel.setText("Adopsi");

        headergambarAdopsiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pawcare.png"))); // NOI18N

        javax.swing.GroupLayout headerAdopsiPanelLayout = new javax.swing.GroupLayout(headerAdopsiPanel);
        headerAdopsiPanel.setLayout(headerAdopsiPanelLayout);
        headerAdopsiPanelLayout.setHorizontalGroup(
            headerAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headergambarAdopsiLabel)
                .addGap(34, 34, 34))
        );
        headerAdopsiPanelLayout.setVerticalGroup(
            headerAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerAdopsiLabel)
                    .addGroup(headerAdopsiPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(headergambarAdopsiLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adopsiButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanAdopsiButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanAdopsiButton.setText("Barukan");
        barukanAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanAdopsiButtonActionPerformed(evt);
            }
        });

        hapusAdopsiButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusAdopsiButton.setText("Hapus");
        hapusAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusAdopsiButtonActionPerformed(evt);
            }
        });

        tambahAdopsiButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahAdopsiButton.setText("Tambah");
        tambahAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAdopsiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adopsiButtonPanelLayout = new javax.swing.GroupLayout(adopsiButtonPanel);
        adopsiButtonPanel.setLayout(adopsiButtonPanelLayout);
        adopsiButtonPanelLayout.setHorizontalGroup(
            adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahAdopsiButton)
                .addGap(18, 18, 18)
                .addComponent(barukanAdopsiButton)
                .addGap(18, 18, 18)
                .addComponent(hapusAdopsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        adopsiButtonPanelLayout.setVerticalGroup(
            adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahAdopsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusAdopsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataAdopsiPanel.setBackground(new java.awt.Color(102, 126, 190));

        tableAdopsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAdopsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdopsiMouseClicked(evt);
            }
        });
        dataAdopsiScrollPane.setViewportView(tableAdopsi);

        dataAdopsiLabel.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        dataAdopsiLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataAdopsiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cells.png"))); // NOI18N
        dataAdopsiLabel.setText("DATA ADOPSI");

        javax.swing.GroupLayout dataAdopsiPanelLayout = new javax.swing.GroupLayout(dataAdopsiPanel);
        dataAdopsiPanel.setLayout(dataAdopsiPanelLayout);
        dataAdopsiPanelLayout.setHorizontalGroup(
            dataAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataAdopsiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dataAdopsiScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataAdopsiPanelLayout.setVerticalGroup(
            dataAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataAdopsiPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dataAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataAdopsiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tyAdopsiPanel.setBackground(new java.awt.Color(238, 242, 250));

        tyAdopsiLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tyAdopsiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pawpink.png"))); // NOI18N
        tyAdopsiLabel.setText("Thank you for choosing adoption and giving them a loving forever home.");

        javax.swing.GroupLayout tyAdopsiPanelLayout = new javax.swing.GroupLayout(tyAdopsiPanel);
        tyAdopsiPanel.setLayout(tyAdopsiPanelLayout);
        tyAdopsiPanelLayout.setHorizontalGroup(
            tyAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tyAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tyAdopsiLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tyAdopsiPanelLayout.setVerticalGroup(
            tyAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tyAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tyAdopsiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerAdopsiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataAdopsiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchAdopsiInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1594, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(adopsiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(adopsiFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(tyAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(batalAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchAdopsiInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adopsiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adopsiFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tyAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataAdopsiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAdopsiInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAdopsiInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchAdopsiInputTextFieldKeyPressed

    private void searchAdopsiInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdopsiInputButtonActionPerformed
       
    }//GEN-LAST:event_searchAdopsiInputButtonActionPerformed

    private void simpanAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_simpanAdopsiButtonActionPerformed

    private void searchAdopsiInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdopsiInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAdopsiInputTextFieldActionPerformed

    private void batalAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_batalAdopsiButtonActionPerformed

    private void namaHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaHewanDropdownActionPerformed

    private void statusAdopsiDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusAdopsiDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusAdopsiDropdownActionPerformed

    private void tambahAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAdopsiButtonActionPerformed

    }//GEN-LAST:event_tambahAdopsiButtonActionPerformed

    private void hapusAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusAdopsiButtonActionPerformed

    }//GEN-LAST:event_hapusAdopsiButtonActionPerformed

    private void barukanAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanAdopsiButtonActionPerformed

    }//GEN-LAST:event_barukanAdopsiButtonActionPerformed

    private void tableAdopsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdopsiMouseClicked

    }//GEN-LAST:event_tableAdopsiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adopsiButtonPanel;
    private javax.swing.JPanel adopsiFormPanel;
    private javax.swing.JLabel alamatAdopterLabel;
    private javax.swing.JPanel alamatAdopterPanel;
    private javax.swing.JScrollPane alamatAdopterScrollPane;
    private javax.swing.JButton barukanAdopsiButton;
    private javax.swing.JButton batalAdopsiButton;
    private javax.swing.JLabel biayaAdopsiLabel;
    private javax.swing.JPanel biayaAdopsiPanel;
    private javax.swing.JTextField biayaAdopsiTextField;
    private javax.swing.JLabel dataAdopsiLabel;
    private javax.swing.JPanel dataAdopsiPanel;
    private javax.swing.JScrollPane dataAdopsiScrollPane;
    private javax.swing.JTextArea deskripsiProdukTextArea;
    private javax.swing.JLabel gamabarAdoptMeLabel;
    private javax.swing.JButton hapusAdopsiButton;
    private javax.swing.JLabel headerAdopsiLabel;
    private javax.swing.JPanel headerAdopsiPanel;
    private javax.swing.JLabel headergambarAdopsiLabel;
    private javax.swing.JLabel idAdopsiLabel;
    private javax.swing.JPanel idAdopsiPanel;
    private javax.swing.JTextField idAdopsiTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaAdopterLabel;
    private javax.swing.JPanel namaAdopterPanel;
    private javax.swing.JTextField namaAdopterTextField;
    private javax.swing.JComboBox<KendaraanE> namaHewanDropdown;
    private javax.swing.JLabel namaHewanLabel;
    private javax.swing.JPanel namaHewanPanel;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JPanel noTeleponPanel;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JButton searchAdopsiInputButton;
    private javax.swing.JLabel searchAdopsiInputLabel;
    private javax.swing.JPanel searchAdopsiInputPanel;
    private javax.swing.JTextField searchAdopsiInputTextField;
    private javax.swing.JButton simpanAdopsiButton;
    private javax.swing.JComboBox<KendaraanE> statusAdopsiDropdown;
    private javax.swing.JLabel statusAdopsiLabel;
    private javax.swing.JPanel statusAdopsiPanel;
    private javax.swing.JTable tableAdopsi;
    private javax.swing.JButton tambahAdopsiButton;
    private com.toedter.calendar.JDateChooser tanggalAdopsiDateChooser;
    private javax.swing.JLabel tanggalAdopsiLabel;
    private javax.swing.JPanel tanggalAdopsiPanel;
    private javax.swing.JLabel tyAdopsiLabel;
    private javax.swing.JPanel tyAdopsiPanel;
    // End of variables declaration//GEN-END:variables
}
