package panelView;

public class AdopsiMainPanel extends javax.swing.JPanel {
    

    public AdopsiMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        adopsiLabel = new javax.swing.JLabel();
        searchAdopsiInputPanel = new javax.swing.JPanel();
        searchAdopsiInputLabel = new javax.swing.JLabel();
        searchAdopsiInputTextField = new javax.swing.JTextField();
        searchAdopsiInputButton = new javax.swing.JButton();
        adopsiFormPanel = new javax.swing.JPanel();
        adopsiButtonPanel = new javax.swing.JPanel();
        barukanAdopsiButton = new javax.swing.JButton();
        hapusAdopsiButton = new javax.swing.JButton();
        tambahAdopsiButton = new javax.swing.JButton();
        idAdopsiPanel = new javax.swing.JPanel();
        idAdopsiLabel = new javax.swing.JLabel();
        idAdopsiTextField = new javax.swing.JTextField();
        namaAdopterPanel = new javax.swing.JPanel();
        namaAdopterLabel = new javax.swing.JLabel();
        namaAdopterTextField = new javax.swing.JTextField();
        noTeleponPanel = new javax.swing.JPanel();
        noTeleponLabel = new javax.swing.JLabel();
        noTeleponTextField = new javax.swing.JTextField();
        namaHewanPanel = new javax.swing.JPanel();
        namaHewanLabel = new javax.swing.JLabel();
        namaHewanDropdown = new javax.swing.JComboBox<>();
        tanggalAdopsiPanel = new javax.swing.JPanel();
        tanggalAdopsiLabel = new javax.swing.JLabel();
        tanggalAdopsiJDateChooser = new com.toedter.calendar.JDateChooser();
        statusAdopsiPanel = new javax.swing.JPanel();
        statusAdopsiLabel = new javax.swing.JLabel();
        statusAdopsiDropdown = new javax.swing.JComboBox<>();
        biayaAdopsiPanel = new javax.swing.JPanel();
        biayaAdopsiLabel = new javax.swing.JLabel();
        biayaAdopsiTextField = new javax.swing.JTextField();
        alamatAdopterPanel = new javax.swing.JPanel();
        alamatAdopterLabel = new javax.swing.JLabel();
        alamatAdopterScrollPane = new javax.swing.JScrollPane();
        deskripsiProdukTextArea = new javax.swing.JTextArea();
        simpanAdopsiButton = new javax.swing.JButton();
        batalAdopsiButton = new javax.swing.JButton();
        adopsiScrollPane = new javax.swing.JScrollPane();
        tableAdopsi = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        adopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        adopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adopsiLabel.setText("ADOPSI");

        searchAdopsiInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchAdopsiInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchAdopsiInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputLabel.setText("Pencarian Adopsi");

        searchAdopsiInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdopsiInputTextFieldActionPerformed(evt);
            }
        });
        searchAdopsiInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchAdopsiInputTextFieldKeyPressed(evt);
            }
        });

        searchAdopsiInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchAdopsiInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAdopsiInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchAdopsiInputButton.setText("Cari");
        searchAdopsiInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdopsiInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchAdopsiInputPanelLayout = new javax.swing.GroupLayout(searchAdopsiInputPanel);
        searchAdopsiInputPanel.setLayout(searchAdopsiInputPanelLayout);
        searchAdopsiInputPanelLayout.setHorizontalGroup(
            searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAdopsiInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                        .addComponent(searchAdopsiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchAdopsiInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchAdopsiInputPanelLayout.setVerticalGroup(
            searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAdopsiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchAdopsiInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchAdopsiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchAdopsiInputTextField)
                    .addComponent(searchAdopsiInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adopsiFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        adopsiButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanAdopsiButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanAdopsiButton.setText("Barukan");
        barukanAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanAdopsiButtonActionPerformed(evt);
            }
        });

        hapusAdopsiButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusAdopsiButton.setText("Hapus");
        hapusAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusAdopsiButtonActionPerformed(evt);
            }
        });

        tambahAdopsiButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahAdopsiButton.setText("Tambah");
        tambahAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAdopsiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adopsiButtonPanelLayout = new javax.swing.GroupLayout(adopsiButtonPanel);
        adopsiButtonPanel.setLayout(adopsiButtonPanelLayout);
        adopsiButtonPanelLayout.setHorizontalGroup(
            adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahAdopsiButton)
                .addGap(18, 18, 18)
                .addComponent(barukanAdopsiButton)
                .addGap(18, 18, 18)
                .addComponent(hapusAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        adopsiButtonPanelLayout.setVerticalGroup(
            adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adopsiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahAdopsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusAdopsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        idAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idAdopsiLabel.setText("ID Adopsi");

        idAdopsiTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idAdopsiPanelLayout = new javax.swing.GroupLayout(idAdopsiPanel);
        idAdopsiPanel.setLayout(idAdopsiPanelLayout);
        idAdopsiPanelLayout.setHorizontalGroup(
            idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(idAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(idAdopsiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        idAdopsiPanelLayout.setVerticalGroup(
            idAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAdopsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaAdopterPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaAdopterPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaAdopterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaAdopterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaAdopterLabel.setText("Nama Adopter");

        namaAdopterTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaAdopterTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout namaAdopterPanelLayout = new javax.swing.GroupLayout(namaAdopterPanel);
        namaAdopterPanel.setLayout(namaAdopterPanelLayout);
        namaAdopterPanelLayout.setHorizontalGroup(
            namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaAdopterPanelLayout.createSequentialGroup()
                        .addComponent(namaAdopterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(namaAdopterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaAdopterPanelLayout.setVerticalGroup(
            namaAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaAdopterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAdopterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponPanel.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        noTeleponLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noTeleponLabel.setText("No Telepon");

        noTeleponTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout noTeleponPanelLayout = new javax.swing.GroupLayout(noTeleponPanel);
        noTeleponPanel.setLayout(noTeleponPanelLayout);
        noTeleponPanelLayout.setHorizontalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noTeleponPanelLayout.createSequentialGroup()
                        .addComponent(noTeleponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        noTeleponPanelLayout.setVerticalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        namaHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaHewanLabel.setText("Nama Hewan");

        namaHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        namaHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaHewanPanelLayout = new javax.swing.GroupLayout(namaHewanPanel);
        namaHewanPanel.setLayout(namaHewanPanelLayout);
        namaHewanPanelLayout.setHorizontalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaHewanPanelLayout.createSequentialGroup()
                        .addComponent(namaHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(namaHewanDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaHewanPanelLayout.setVerticalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tanggalAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        tanggalAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        tanggalAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalAdopsiLabel.setText("Tanggal Adopsi");

        tanggalAdopsiJDateChooser.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout tanggalAdopsiPanelLayout = new javax.swing.GroupLayout(tanggalAdopsiPanel);
        tanggalAdopsiPanel.setLayout(tanggalAdopsiPanelLayout);
        tanggalAdopsiPanelLayout.setHorizontalGroup(
            tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tanggalAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(tanggalAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(tanggalAdopsiJDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tanggalAdopsiPanelLayout.setVerticalGroup(
            tanggalAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalAdopsiJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        statusAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        statusAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        statusAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAdopsiLabel.setText("Status Adopsi");

        statusAdopsiDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusAdopsiDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        statusAdopsiDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusAdopsiDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusAdopsiPanelLayout = new javax.swing.GroupLayout(statusAdopsiPanel);
        statusAdopsiPanel.setLayout(statusAdopsiPanelLayout);
        statusAdopsiPanelLayout.setHorizontalGroup(
            statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(statusAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(statusAdopsiDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusAdopsiPanelLayout.setVerticalGroup(
            statusAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAdopsiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        biayaAdopsiPanel.setBackground(new java.awt.Color(255, 255, 255));
        biayaAdopsiPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        biayaAdopsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        biayaAdopsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        biayaAdopsiLabel.setText("Biaya Adopsi");

        biayaAdopsiTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout biayaAdopsiPanelLayout = new javax.swing.GroupLayout(biayaAdopsiPanel);
        biayaAdopsiPanel.setLayout(biayaAdopsiPanelLayout);
        biayaAdopsiPanelLayout.setHorizontalGroup(
            biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biayaAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biayaAdopsiPanelLayout.createSequentialGroup()
                        .addComponent(biayaAdopsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(biayaAdopsiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        biayaAdopsiPanelLayout.setVerticalGroup(
            biayaAdopsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biayaAdopsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biayaAdopsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaAdopsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alamatAdopterPanel.setBackground(new java.awt.Color(255, 255, 255));
        alamatAdopterPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        alamatAdopterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatAdopterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alamatAdopterLabel.setText("Alamat");

        deskripsiProdukTextArea.setColumns(20);
        deskripsiProdukTextArea.setRows(5);
        alamatAdopterScrollPane.setViewportView(deskripsiProdukTextArea);

        javax.swing.GroupLayout alamatAdopterPanelLayout = new javax.swing.GroupLayout(alamatAdopterPanel);
        alamatAdopterPanel.setLayout(alamatAdopterPanelLayout);
        alamatAdopterPanelLayout.setHorizontalGroup(
            alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatAdopterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatAdopterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alamatAdopterPanelLayout.setVerticalGroup(
            alamatAdopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatAdopterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatAdopterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatAdopterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout adopsiFormPanelLayout = new javax.swing.GroupLayout(adopsiFormPanel);
        adopsiFormPanel.setLayout(adopsiFormPanelLayout);
        adopsiFormPanelLayout.setHorizontalGroup(
            adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addComponent(adopsiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaAdopterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(biayaAdopsiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamatAdopterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 217, Short.MAX_VALUE))))
        );
        adopsiFormPanelLayout.setVerticalGroup(
            adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adopsiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaAdopterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adopsiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(adopsiFormPanelLayout.createSequentialGroup()
                        .addComponent(biayaAdopsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatAdopterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addContainerGap())
        );

        simpanAdopsiButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanAdopsiButton.setText("Simpan");
        simpanAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanAdopsiButtonActionPerformed(evt);
            }
        });

        batalAdopsiButton.setBackground(new java.awt.Color(237, 8, 0));
        batalAdopsiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalAdopsiButton.setForeground(new java.awt.Color(255, 255, 255));
        batalAdopsiButton.setText("Batalkan");
        batalAdopsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalAdopsiButtonActionPerformed(evt);
            }
        });

        adopsiScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tableAdopsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAdopsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdopsiMouseClicked(evt);
            }
        });
        adopsiScrollPane.setViewportView(tableAdopsi);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adopsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchAdopsiInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
                            .addComponent(adopsiFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(simpanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(batalAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(adopsiScrollPane)
                        .addGap(42, 42, 42))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(adopsiLabel)
                .addGap(18, 18, 18)
                .addComponent(searchAdopsiInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adopsiFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalAdopsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adopsiScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAdopsiInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAdopsiInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchAdopsiInputTextFieldKeyPressed

    private void searchAdopsiInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdopsiInputButtonActionPerformed
       
    }//GEN-LAST:event_searchAdopsiInputButtonActionPerformed

    private void barukanAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_barukanAdopsiButtonActionPerformed

    private void hapusAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_hapusAdopsiButtonActionPerformed

    private void tambahAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_tambahAdopsiButtonActionPerformed

    private void simpanAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_simpanAdopsiButtonActionPerformed

    private void searchAdopsiInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdopsiInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAdopsiInputTextFieldActionPerformed

    private void batalAdopsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalAdopsiButtonActionPerformed
        
    }//GEN-LAST:event_batalAdopsiButtonActionPerformed

    private void tableAdopsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdopsiMouseClicked
        
    }//GEN-LAST:event_tableAdopsiMouseClicked

    private void namaHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaHewanDropdownActionPerformed

    private void statusAdopsiDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusAdopsiDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusAdopsiDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adopsiButtonPanel;
    private javax.swing.JPanel adopsiFormPanel;
    private javax.swing.JLabel adopsiLabel;
    private javax.swing.JScrollPane adopsiScrollPane;
    private javax.swing.JLabel alamatAdopterLabel;
    private javax.swing.JPanel alamatAdopterPanel;
    private javax.swing.JScrollPane alamatAdopterScrollPane;
    private javax.swing.JButton barukanAdopsiButton;
    private javax.swing.JButton batalAdopsiButton;
    private javax.swing.JLabel biayaAdopsiLabel;
    private javax.swing.JPanel biayaAdopsiPanel;
    private javax.swing.JTextField biayaAdopsiTextField;
    private javax.swing.JTextArea deskripsiProdukTextArea;
    private javax.swing.JButton hapusAdopsiButton;
    private javax.swing.JLabel idAdopsiLabel;
    private javax.swing.JPanel idAdopsiPanel;
    private javax.swing.JTextField idAdopsiTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaAdopterLabel;
    private javax.swing.JPanel namaAdopterPanel;
    private javax.swing.JTextField namaAdopterTextField;
    private javax.swing.JComboBox<KendaraanE> namaHewanDropdown;
    private javax.swing.JLabel namaHewanLabel;
    private javax.swing.JPanel namaHewanPanel;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JPanel noTeleponPanel;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JButton searchAdopsiInputButton;
    private javax.swing.JLabel searchAdopsiInputLabel;
    private javax.swing.JPanel searchAdopsiInputPanel;
    private javax.swing.JTextField searchAdopsiInputTextField;
    private javax.swing.JButton simpanAdopsiButton;
    private javax.swing.JComboBox<KendaraanE> statusAdopsiDropdown;
    private javax.swing.JLabel statusAdopsiLabel;
    private javax.swing.JPanel statusAdopsiPanel;
    private javax.swing.JTable tableAdopsi;
    private javax.swing.JButton tambahAdopsiButton;
    private com.toedter.calendar.JDateChooser tanggalAdopsiJDateChooser;
    private javax.swing.JLabel tanggalAdopsiLabel;
    private javax.swing.JPanel tanggalAdopsiPanel;
    // End of variables declaration//GEN-END:variables
}
