package panelView;

public class HewanMainPanel extends javax.swing.JPanel {
    

    public HewanMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        hewanLabel = new javax.swing.JLabel();
        searchHewanInputPanel = new javax.swing.JPanel();
        searchHewanInputLabel = new javax.swing.JLabel();
        searchHewanInputTextField = new javax.swing.JTextField();
        searchHewanInputButton = new javax.swing.JButton();
        hewanFormPanel = new javax.swing.JPanel();
        hewanButtonPanel = new javax.swing.JPanel();
        barukanHewanButton = new javax.swing.JButton();
        hapusHewanButton = new javax.swing.JButton();
        tambahHewanButton = new javax.swing.JButton();
        idHewanPanel = new javax.swing.JPanel();
        idHewanLabel = new javax.swing.JLabel();
        idHewanTextField = new javax.swing.JTextField();
        jenisHewanPanel = new javax.swing.JPanel();
        jenisHewanLabel = new javax.swing.JLabel();
        jenisHewanDropdown = new javax.swing.JComboBox<>();
        umurHewanPanel = new javax.swing.JPanel();
        umurHewanLabel = new javax.swing.JLabel();
        umurHewanTextField = new javax.swing.JTextField();
        namaHewanPanel = new javax.swing.JPanel();
        namaHewanLabel = new javax.swing.JLabel();
        namaHewanTextField = new javax.swing.JTextField();
        warnaHewanPanel = new javax.swing.JPanel();
        warnaHewanLabel = new javax.swing.JLabel();
        warnaHewanTextField = new javax.swing.JTextField();
        genderHewanPanel = new javax.swing.JPanel();
        genderHewanLabel = new javax.swing.JLabel();
        genderHewanDropdown = new javax.swing.JComboBox<>();
        statusHewanPanel = new javax.swing.JPanel();
        statusHewanLabel = new javax.swing.JLabel();
        statusHewanDropdown = new javax.swing.JComboBox<>();
        simpanHewanButton = new javax.swing.JButton();
        batalHewanButton = new javax.swing.JButton();
        hewanScrollPane = new javax.swing.JScrollPane();
        tableHewan = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        hewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        hewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hewanLabel.setText("HEWAN");

        searchHewanInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchHewanInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchHewanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchHewanInputLabel.setText("Pencarian Hewan");

        searchHewanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchHewanInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHewanInputTextFieldActionPerformed(evt);
            }
        });
        searchHewanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchHewanInputTextFieldKeyPressed(evt);
            }
        });

        searchHewanInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchHewanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchHewanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchHewanInputButton.setText("Cari");
        searchHewanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHewanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchHewanInputPanelLayout = new javax.swing.GroupLayout(searchHewanInputPanel);
        searchHewanInputPanel.setLayout(searchHewanInputPanelLayout);
        searchHewanInputPanelLayout.setHorizontalGroup(
            searchHewanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchHewanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchHewanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchHewanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchHewanInputPanelLayout.createSequentialGroup()
                        .addComponent(searchHewanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchHewanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchHewanInputPanelLayout.setVerticalGroup(
            searchHewanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchHewanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchHewanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchHewanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchHewanInputTextField)
                    .addComponent(searchHewanInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hewanFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        hewanButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanHewanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanHewanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanHewanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanHewanButton.setText("Barukan");
        barukanHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanHewanButtonActionPerformed(evt);
            }
        });

        hapusHewanButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusHewanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusHewanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusHewanButton.setText("Hapus");
        hapusHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusHewanButtonActionPerformed(evt);
            }
        });

        tambahHewanButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahHewanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahHewanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahHewanButton.setText("Tambah");
        tambahHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahHewanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hewanButtonPanelLayout = new javax.swing.GroupLayout(hewanButtonPanel);
        hewanButtonPanel.setLayout(hewanButtonPanelLayout);
        hewanButtonPanelLayout.setHorizontalGroup(
            hewanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahHewanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanHewanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        hewanButtonPanelLayout.setVerticalGroup(
            hewanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hewanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahHewanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusHewanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        idHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idHewanLabel.setText("ID Hewan");

        idHewanTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idHewanPanelLayout = new javax.swing.GroupLayout(idHewanPanel);
        idHewanPanel.setLayout(idHewanPanelLayout);
        idHewanPanelLayout.setHorizontalGroup(
            idHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idHewanPanelLayout.createSequentialGroup()
                        .addComponent(idHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(idHewanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        idHewanPanelLayout.setVerticalGroup(
            idHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idHewanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jenisHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        jenisHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        jenisHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jenisHewanLabel.setText("Jenis Hewan");

        jenisHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        jenisHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenisHewanPanelLayout = new javax.swing.GroupLayout(jenisHewanPanel);
        jenisHewanPanel.setLayout(jenisHewanPanelLayout);
        jenisHewanPanelLayout.setHorizontalGroup(
            jenisHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisHewanPanelLayout.createSequentialGroup()
                        .addComponent(jenisHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(jenisHewanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jenisHewanPanelLayout.setVerticalGroup(
            jenisHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenisHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        umurHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        umurHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        umurHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        umurHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        umurHewanLabel.setText("Umur Hewan");

        umurHewanTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        umurHewanTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout umurHewanPanelLayout = new javax.swing.GroupLayout(umurHewanPanel);
        umurHewanPanel.setLayout(umurHewanPanelLayout);
        umurHewanPanelLayout.setHorizontalGroup(
            umurHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(umurHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(umurHewanPanelLayout.createSequentialGroup()
                        .addComponent(umurHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(umurHewanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        umurHewanPanelLayout.setVerticalGroup(
            umurHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, umurHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(umurHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurHewanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaHewanLabel.setText("Nama Hewan");

        namaHewanTextField.setPreferredSize(new java.awt.Dimension(72, 21));
        namaHewanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaHewanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaHewanPanelLayout = new javax.swing.GroupLayout(namaHewanPanel);
        namaHewanPanel.setLayout(namaHewanPanelLayout);
        namaHewanPanelLayout.setHorizontalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaHewanPanelLayout.createSequentialGroup()
                        .addComponent(namaHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(namaHewanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaHewanPanelLayout.setVerticalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaHewanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        warnaHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        warnaHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        warnaHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        warnaHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        warnaHewanLabel.setText("Warna Hewan");

        warnaHewanTextField.setPreferredSize(new java.awt.Dimension(72, 21));
        warnaHewanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaHewanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warnaHewanPanelLayout = new javax.swing.GroupLayout(warnaHewanPanel);
        warnaHewanPanel.setLayout(warnaHewanPanelLayout);
        warnaHewanPanelLayout.setHorizontalGroup(
            warnaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warnaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warnaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warnaHewanPanelLayout.createSequentialGroup()
                        .addComponent(warnaHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(warnaHewanTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        warnaHewanPanelLayout.setVerticalGroup(
            warnaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warnaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warnaHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnaHewanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        genderHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        genderHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        genderHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        genderHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genderHewanLabel.setText("Gender Hewan");

        genderHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        genderHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        genderHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genderHewanPanelLayout = new javax.swing.GroupLayout(genderHewanPanel);
        genderHewanPanel.setLayout(genderHewanPanelLayout);
        genderHewanPanelLayout.setHorizontalGroup(
            genderHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genderHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genderHewanPanelLayout.createSequentialGroup()
                        .addComponent(genderHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(genderHewanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        genderHewanPanelLayout.setVerticalGroup(
            genderHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genderHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genderHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        statusHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        statusHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusHewanLabel.setText("Status");

        statusHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        statusHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusHewanPanelLayout = new javax.swing.GroupLayout(statusHewanPanel);
        statusHewanPanel.setLayout(statusHewanPanelLayout);
        statusHewanPanelLayout.setHorizontalGroup(
            statusHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusHewanPanelLayout.createSequentialGroup()
                        .addComponent(statusHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(statusHewanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusHewanPanelLayout.setVerticalGroup(
            statusHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hewanFormPanelLayout = new javax.swing.GroupLayout(hewanFormPanel);
        hewanFormPanel.setLayout(hewanFormPanelLayout);
        hewanFormPanelLayout.setHorizontalGroup(
            hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hewanFormPanelLayout.createSequentialGroup()
                        .addComponent(hewanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hewanFormPanelLayout.createSequentialGroup()
                        .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(umurHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warnaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hewanFormPanelLayout.createSequentialGroup()
                                .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(statusHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(genderHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 206, Short.MAX_VALUE))))
        );
        hewanFormPanelLayout.setVerticalGroup(
            hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hewanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hewanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warnaHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hewanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(umurHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderHewanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanHewanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanHewanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanHewanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanHewanButton.setText("Simpan");
        simpanHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanHewanButtonActionPerformed(evt);
            }
        });

        batalHewanButton.setBackground(new java.awt.Color(237, 8, 0));
        batalHewanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalHewanButton.setForeground(new java.awt.Color(255, 255, 255));
        batalHewanButton.setText("Batalkan");
        batalHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalHewanButtonActionPerformed(evt);
            }
        });

        hewanScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tableHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHewanMouseClicked(evt);
            }
        });
        hewanScrollPane.setViewportView(tableHewan);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchHewanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                    .addComponent(hewanScrollPane)
                    .addComponent(hewanFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batalHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(hewanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(hewanLabel)
                .addGap(18, 18, 18)
                .addComponent(searchHewanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hewanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hewanScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchHewanInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchHewanInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchHewanInputTextFieldKeyPressed

    private void searchHewanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchHewanInputButtonActionPerformed
       
    }//GEN-LAST:event_searchHewanInputButtonActionPerformed

    private void barukanHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanHewanButtonActionPerformed
        
    }//GEN-LAST:event_barukanHewanButtonActionPerformed

    private void hapusHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusHewanButtonActionPerformed
        
    }//GEN-LAST:event_hapusHewanButtonActionPerformed

    private void tambahHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahHewanButtonActionPerformed
        
    }//GEN-LAST:event_tambahHewanButtonActionPerformed

    private void simpanHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanHewanButtonActionPerformed
        
    }//GEN-LAST:event_simpanHewanButtonActionPerformed

    private void searchHewanInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchHewanInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchHewanInputTextFieldActionPerformed

    private void jenisHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisHewanDropdownActionPerformed

    private void batalHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalHewanButtonActionPerformed
        
    }//GEN-LAST:event_batalHewanButtonActionPerformed

    private void tableHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHewanMouseClicked
        
    }//GEN-LAST:event_tableHewanMouseClicked

    private void namaHewanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaHewanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaHewanTextFieldActionPerformed

    private void warnaHewanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnaHewanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warnaHewanTextFieldActionPerformed

    private void genderHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderHewanDropdownActionPerformed

    private void statusHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusHewanDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanHewanButton;
    private javax.swing.JButton batalHewanButton;
    private javax.swing.JComboBox<KendaraanE> genderHewanDropdown;
    private javax.swing.JLabel genderHewanLabel;
    private javax.swing.JPanel genderHewanPanel;
    private javax.swing.JButton hapusHewanButton;
    private javax.swing.JPanel hewanButtonPanel;
    private javax.swing.JPanel hewanFormPanel;
    private javax.swing.JLabel hewanLabel;
    private javax.swing.JScrollPane hewanScrollPane;
    private javax.swing.JLabel idHewanLabel;
    private javax.swing.JPanel idHewanPanel;
    private javax.swing.JTextField idHewanTextField;
    private javax.swing.JComboBox<KendaraanE> jenisHewanDropdown;
    private javax.swing.JLabel jenisHewanLabel;
    private javax.swing.JPanel jenisHewanPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaHewanLabel;
    private javax.swing.JPanel namaHewanPanel;
    private javax.swing.JTextField namaHewanTextField;
    private javax.swing.JButton searchHewanInputButton;
    private javax.swing.JLabel searchHewanInputLabel;
    private javax.swing.JPanel searchHewanInputPanel;
    private javax.swing.JTextField searchHewanInputTextField;
    private javax.swing.JButton simpanHewanButton;
    private javax.swing.JComboBox<KendaraanE> statusHewanDropdown;
    private javax.swing.JLabel statusHewanLabel;
    private javax.swing.JPanel statusHewanPanel;
    private javax.swing.JTable tableHewan;
    private javax.swing.JButton tambahHewanButton;
    private javax.swing.JLabel umurHewanLabel;
    private javax.swing.JPanel umurHewanPanel;
    private javax.swing.JTextField umurHewanTextField;
    private javax.swing.JLabel warnaHewanLabel;
    private javax.swing.JPanel warnaHewanPanel;
    private javax.swing.JTextField warnaHewanTextField;
    // End of variables declaration//GEN-END:variables
}
