package panelView;

public class PenitipanMainPanel extends javax.swing.JPanel {
    

    public PenitipanMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        penitipanLabel = new javax.swing.JLabel();
        searchPenitipanInputPanel = new javax.swing.JPanel();
        searchPenitipanInputLabel = new javax.swing.JLabel();
        searchPenitipanInputTextField = new javax.swing.JTextField();
        searchPenitipanInputButton = new javax.swing.JButton();
        penitipanFormPanel = new javax.swing.JPanel();
        penitipanButtonPanel = new javax.swing.JPanel();
        barukanPenitipanButton = new javax.swing.JButton();
        hapusPenitipanButton = new javax.swing.JButton();
        tambahPenitipanButton = new javax.swing.JButton();
        idPenitipanPanel = new javax.swing.JPanel();
        idPenitipanLabel = new javax.swing.JLabel();
        idPenitipanTextField = new javax.swing.JTextField();
        namaPemilikPanel = new javax.swing.JPanel();
        namaPemilikLabel = new javax.swing.JLabel();
        namaPemilikTextField = new javax.swing.JTextField();
        noTeleponPanel = new javax.swing.JPanel();
        noTeleponLabel = new javax.swing.JLabel();
        noTeleponTextField = new javax.swing.JTextField();
        namaHewanPanel = new javax.swing.JPanel();
        namaHewanLabel = new javax.swing.JLabel();
        namaHewanDropdown = new javax.swing.JComboBox<>();
        tanggalMasukPanel = new javax.swing.JPanel();
        tanggalMasukLabel = new javax.swing.JLabel();
        tanggalMasukJDateChooser = new com.toedter.calendar.JDateChooser();
        tanggalKeluarPanel = new javax.swing.JPanel();
        tanggalKeluarLabel = new javax.swing.JLabel();
        tanggalKeluarJDateChooser = new com.toedter.calendar.JDateChooser();
        durasiPenitipanPanel = new javax.swing.JPanel();
        durasiPenitipanLabel = new javax.swing.JLabel();
        durasiPenitipanTextField = new javax.swing.JTextField();
        biayaPenitipanPanel = new javax.swing.JPanel();
        biayaPenitipanLabel = new javax.swing.JLabel();
        biayaPenitipanTextField = new javax.swing.JTextField();
        statusPenitipanPanel = new javax.swing.JPanel();
        statusPenitipanLabel = new javax.swing.JLabel();
        statusPenitipanDropdown = new javax.swing.JComboBox<>();
        catatanPenitipanPanel = new javax.swing.JPanel();
        catatanPenitipanLabel = new javax.swing.JLabel();
        catatanPenitipanScrollPane = new javax.swing.JScrollPane();
        deskripsiProdukTextArea = new javax.swing.JTextArea();
        simpanPenitipanButton = new javax.swing.JButton();
        batalPenitipanButton = new javax.swing.JButton();
        penitipanScrollPane = new javax.swing.JScrollPane();
        tablePenitipan = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        penitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        penitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penitipanLabel.setText("PENITIPAN");

        searchPenitipanInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPenitipanInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchPenitipanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPenitipanInputLabel.setText("Pencarian Penitipan");

        searchPenitipanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPenitipanInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPenitipanInputTextFieldActionPerformed(evt);
            }
        });
        searchPenitipanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchPenitipanInputTextFieldKeyPressed(evt);
            }
        });

        searchPenitipanInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchPenitipanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPenitipanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPenitipanInputButton.setText("Cari");
        searchPenitipanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPenitipanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPenitipanInputPanelLayout = new javax.swing.GroupLayout(searchPenitipanInputPanel);
        searchPenitipanInputPanel.setLayout(searchPenitipanInputPanelLayout);
        searchPenitipanInputPanelLayout.setHorizontalGroup(
            searchPenitipanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPenitipanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPenitipanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPenitipanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPenitipanInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPenitipanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPenitipanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 556, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPenitipanInputPanelLayout.setVerticalGroup(
            searchPenitipanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPenitipanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPenitipanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPenitipanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPenitipanInputTextField)
                    .addComponent(searchPenitipanInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        penitipanFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        penitipanButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanPenitipanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPenitipanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanPenitipanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPenitipanButton.setText("Barukan");
        barukanPenitipanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPenitipanButtonActionPerformed(evt);
            }
        });

        hapusPenitipanButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPenitipanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusPenitipanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPenitipanButton.setText("Hapus");
        hapusPenitipanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenitipanButtonActionPerformed(evt);
            }
        });

        tambahPenitipanButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPenitipanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahPenitipanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPenitipanButton.setText("Tambah");
        tambahPenitipanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenitipanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout penitipanButtonPanelLayout = new javax.swing.GroupLayout(penitipanButtonPanel);
        penitipanButtonPanel.setLayout(penitipanButtonPanelLayout);
        penitipanButtonPanelLayout.setHorizontalGroup(
            penitipanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPenitipanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanPenitipanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        penitipanButtonPanelLayout.setVerticalGroup(
            penitipanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penitipanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPenitipanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusPenitipanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPenitipanPanel.setBackground(new java.awt.Color(255, 255, 255));
        idPenitipanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idPenitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPenitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idPenitipanLabel.setText("ID Penitipan");

        idPenitipanTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idPenitipanPanelLayout = new javax.swing.GroupLayout(idPenitipanPanel);
        idPenitipanPanel.setLayout(idPenitipanPanelLayout);
        idPenitipanPanelLayout.setHorizontalGroup(
            idPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPenitipanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPenitipanPanelLayout.setVerticalGroup(
            idPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPenitipanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPemilikPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaPemilikPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaPemilikLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPemilikLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaPemilikLabel.setText("Nama Pemilik");

        namaPemilikTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout namaPemilikPanelLayout = new javax.swing.GroupLayout(namaPemilikPanel);
        namaPemilikPanel.setLayout(namaPemilikPanelLayout);
        namaPemilikPanelLayout.setHorizontalGroup(
            namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPemilikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPemilikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPemilikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPemilikPanelLayout.setVerticalGroup(
            namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaPemilikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPemilikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPemilikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponPanel.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        noTeleponLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noTeleponLabel.setText("No Telepon");

        noTeleponTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout noTeleponPanelLayout = new javax.swing.GroupLayout(noTeleponPanel);
        noTeleponPanel.setLayout(noTeleponPanelLayout);
        noTeleponPanelLayout.setHorizontalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTeleponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noTeleponPanelLayout.setVerticalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaHewanPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaHewanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaHewanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaHewanLabel.setText("Nama Hewan");

        namaHewanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaHewanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        namaHewanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaHewanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaHewanPanelLayout = new javax.swing.GroupLayout(namaHewanPanel);
        namaHewanPanel.setLayout(namaHewanPanelLayout);
        namaHewanPanelLayout.setHorizontalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaHewanPanelLayout.createSequentialGroup()
                        .addComponent(namaHewanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(namaHewanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaHewanPanelLayout.setVerticalGroup(
            namaHewanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaHewanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaHewanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaHewanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tanggalMasukPanel.setBackground(new java.awt.Color(255, 255, 255));
        tanggalMasukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        tanggalMasukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalMasukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalMasukLabel.setText("Tanggal Masuk");

        tanggalMasukJDateChooser.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout tanggalMasukPanelLayout = new javax.swing.GroupLayout(tanggalMasukPanel);
        tanggalMasukPanel.setLayout(tanggalMasukPanelLayout);
        tanggalMasukPanelLayout.setHorizontalGroup(
            tanggalMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalMasukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalMasukJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tanggalMasukPanelLayout.setVerticalGroup(
            tanggalMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalMasukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalMasukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalMasukJDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        tanggalKeluarPanel.setBackground(new java.awt.Color(255, 255, 255));
        tanggalKeluarPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        tanggalKeluarLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalKeluarLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalKeluarLabel.setText("Tanggal Keluar");

        tanggalKeluarJDateChooser.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout tanggalKeluarPanelLayout = new javax.swing.GroupLayout(tanggalKeluarPanel);
        tanggalKeluarPanel.setLayout(tanggalKeluarPanelLayout);
        tanggalKeluarPanelLayout.setHorizontalGroup(
            tanggalKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalKeluarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tanggalKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalKeluarJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalKeluarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tanggalKeluarPanelLayout.setVerticalGroup(
            tanggalKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalKeluarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalKeluarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalKeluarJDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        durasiPenitipanPanel.setBackground(new java.awt.Color(255, 255, 255));
        durasiPenitipanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        durasiPenitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        durasiPenitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        durasiPenitipanLabel.setText("Durasi (Hari)");

        durasiPenitipanTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout durasiPenitipanPanelLayout = new javax.swing.GroupLayout(durasiPenitipanPanel);
        durasiPenitipanPanel.setLayout(durasiPenitipanPanelLayout);
        durasiPenitipanPanelLayout.setHorizontalGroup(
            durasiPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durasiPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(durasiPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durasiPenitipanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durasiPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        durasiPenitipanPanelLayout.setVerticalGroup(
            durasiPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, durasiPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(durasiPenitipanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durasiPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        biayaPenitipanPanel.setBackground(new java.awt.Color(255, 255, 255));
        biayaPenitipanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        biayaPenitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        biayaPenitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        biayaPenitipanLabel.setText("Biaya Penitipan");

        biayaPenitipanTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout biayaPenitipanPanelLayout = new javax.swing.GroupLayout(biayaPenitipanPanel);
        biayaPenitipanPanel.setLayout(biayaPenitipanPanelLayout);
        biayaPenitipanPanelLayout.setHorizontalGroup(
            biayaPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biayaPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biayaPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biayaPenitipanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        biayaPenitipanPanelLayout.setVerticalGroup(
            biayaPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biayaPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biayaPenitipanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaPenitipanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusPenitipanPanel.setBackground(new java.awt.Color(255, 255, 255));
        statusPenitipanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        statusPenitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusPenitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusPenitipanLabel.setText("Status Penitipan");

        statusPenitipanDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        statusPenitipanDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        statusPenitipanDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusPenitipanDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPenitipanPanelLayout = new javax.swing.GroupLayout(statusPenitipanPanel);
        statusPenitipanPanel.setLayout(statusPenitipanPanelLayout);
        statusPenitipanPanelLayout.setHorizontalGroup(
            statusPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPenitipanPanelLayout.createSequentialGroup()
                        .addComponent(statusPenitipanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(statusPenitipanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusPenitipanPanelLayout.setVerticalGroup(
            statusPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusPenitipanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPenitipanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        catatanPenitipanPanel.setBackground(new java.awt.Color(255, 255, 255));
        catatanPenitipanPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        catatanPenitipanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        catatanPenitipanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        catatanPenitipanLabel.setText("Catatan");

        deskripsiProdukTextArea.setColumns(20);
        deskripsiProdukTextArea.setRows(5);
        catatanPenitipanScrollPane.setViewportView(deskripsiProdukTextArea);

        javax.swing.GroupLayout catatanPenitipanPanelLayout = new javax.swing.GroupLayout(catatanPenitipanPanel);
        catatanPenitipanPanel.setLayout(catatanPenitipanPanelLayout);
        catatanPenitipanPanelLayout.setHorizontalGroup(
            catatanPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatanPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catatanPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanPenitipanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catatanPenitipanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catatanPenitipanPanelLayout.setVerticalGroup(
            catatanPenitipanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatanPenitipanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catatanPenitipanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatanPenitipanScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout penitipanFormPanelLayout = new javax.swing.GroupLayout(penitipanFormPanel);
        penitipanFormPanel.setLayout(penitipanFormPanelLayout);
        penitipanFormPanelLayout.setHorizontalGroup(
            penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                        .addComponent(penitipanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                                .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idPenitipanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(noTeleponPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaPemilikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(namaHewanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalMasukPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durasiPenitipanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(statusPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(tanggalKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penitipanFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(biayaPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(catatanPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        penitipanFormPanelLayout.setVerticalGroup(
            penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penitipanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaPemilikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noTeleponPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaHewanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggalKeluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalMasukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durasiPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biayaPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(penitipanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusPenitipanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(penitipanFormPanelLayout.createSequentialGroup()
                                .addComponent(catatanPenitipanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addContainerGap())))))
        );

        simpanPenitipanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanPenitipanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanPenitipanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPenitipanButton.setText("Simpan");
        simpanPenitipanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPenitipanButtonActionPerformed(evt);
            }
        });

        batalPenitipanButton.setBackground(new java.awt.Color(237, 8, 0));
        batalPenitipanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalPenitipanButton.setForeground(new java.awt.Color(255, 255, 255));
        batalPenitipanButton.setText("Batalkan");
        batalPenitipanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPenitipanButtonActionPerformed(evt);
            }
        });

        penitipanScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tablePenitipan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenitipan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenitipanMouseClicked(evt);
            }
        });
        penitipanScrollPane.setViewportView(tablePenitipan);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPenitipanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
                    .addComponent(penitipanScrollPane)
                    .addComponent(penitipanFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batalPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(penitipanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(penitipanLabel)
                .addGap(18, 18, 18)
                .addComponent(searchPenitipanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penitipanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalPenitipanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(penitipanScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPenitipanInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPenitipanInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchPenitipanInputTextFieldKeyPressed

    private void searchPenitipanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPenitipanInputButtonActionPerformed
       
    }//GEN-LAST:event_searchPenitipanInputButtonActionPerformed

    private void barukanPenitipanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPenitipanButtonActionPerformed
        
    }//GEN-LAST:event_barukanPenitipanButtonActionPerformed

    private void hapusPenitipanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenitipanButtonActionPerformed
        
    }//GEN-LAST:event_hapusPenitipanButtonActionPerformed

    private void tambahPenitipanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenitipanButtonActionPerformed
        
    }//GEN-LAST:event_tambahPenitipanButtonActionPerformed

    private void simpanPenitipanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPenitipanButtonActionPerformed
        
    }//GEN-LAST:event_simpanPenitipanButtonActionPerformed

    private void searchPenitipanInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPenitipanInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPenitipanInputTextFieldActionPerformed

    private void batalPenitipanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPenitipanButtonActionPerformed
        
    }//GEN-LAST:event_batalPenitipanButtonActionPerformed

    private void tablePenitipanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenitipanMouseClicked
        
    }//GEN-LAST:event_tablePenitipanMouseClicked

    private void namaHewanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaHewanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaHewanDropdownActionPerformed

    private void statusPenitipanDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusPenitipanDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusPenitipanDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanPenitipanButton;
    private javax.swing.JButton batalPenitipanButton;
    private javax.swing.JLabel biayaPenitipanLabel;
    private javax.swing.JPanel biayaPenitipanPanel;
    private javax.swing.JTextField biayaPenitipanTextField;
    private javax.swing.JLabel catatanPenitipanLabel;
    private javax.swing.JPanel catatanPenitipanPanel;
    private javax.swing.JScrollPane catatanPenitipanScrollPane;
    private javax.swing.JTextArea deskripsiProdukTextArea;
    private javax.swing.JLabel durasiPenitipanLabel;
    private javax.swing.JPanel durasiPenitipanPanel;
    private javax.swing.JTextField durasiPenitipanTextField;
    private javax.swing.JButton hapusPenitipanButton;
    private javax.swing.JLabel idPenitipanLabel;
    private javax.swing.JPanel idPenitipanPanel;
    private javax.swing.JTextField idPenitipanTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<KendaraanE> namaHewanDropdown;
    private javax.swing.JLabel namaHewanLabel;
    private javax.swing.JPanel namaHewanPanel;
    private javax.swing.JLabel namaPemilikLabel;
    private javax.swing.JPanel namaPemilikPanel;
    private javax.swing.JTextField namaPemilikTextField;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JPanel noTeleponPanel;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JPanel penitipanButtonPanel;
    private javax.swing.JPanel penitipanFormPanel;
    private javax.swing.JLabel penitipanLabel;
    private javax.swing.JScrollPane penitipanScrollPane;
    private javax.swing.JButton searchPenitipanInputButton;
    private javax.swing.JLabel searchPenitipanInputLabel;
    private javax.swing.JPanel searchPenitipanInputPanel;
    private javax.swing.JTextField searchPenitipanInputTextField;
    private javax.swing.JButton simpanPenitipanButton;
    private javax.swing.JComboBox<KendaraanE> statusPenitipanDropdown;
    private javax.swing.JLabel statusPenitipanLabel;
    private javax.swing.JPanel statusPenitipanPanel;
    private javax.swing.JTable tablePenitipan;
    private javax.swing.JButton tambahPenitipanButton;
    private com.toedter.calendar.JDateChooser tanggalKeluarJDateChooser;
    private javax.swing.JLabel tanggalKeluarLabel;
    private javax.swing.JPanel tanggalKeluarPanel;
    private com.toedter.calendar.JDateChooser tanggalMasukJDateChooser;
    private javax.swing.JLabel tanggalMasukLabel;
    private javax.swing.JPanel tanggalMasukPanel;
    // End of variables declaration//GEN-END:variables
}
