package panelView;

public class PenjualanMainPanel extends javax.swing.JPanel {
    

    public PenjualanMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        customerManagementPanel = new javax.swing.JPanel();
        customerIconLabel = new javax.swing.JLabel();
        customerManagementLabel = new javax.swing.JLabel();
        customerManagementLabel2 = new javax.swing.JLabel();
        searchCustomerInputPanel = new javax.swing.JPanel();
        searchCustomerIconLabel = new javax.swing.JLabel();
        searchCustomerInputTextField = new javax.swing.JTextField();
        searchCustomerInputButton = new javax.swing.JButton();
        customerFormPanel = new javax.swing.JPanel();
        formCustomerLabel = new javax.swing.JLabel();
        customerButtonPanel = new javax.swing.JPanel();
        barukanCustomerButton = new javax.swing.JButton();
        hapusCustomerButton = new javax.swing.JButton();
        tambahCustomerButton = new javax.swing.JButton();
        idCustomerPanel = new javax.swing.JPanel();
        idCustomerLabel = new javax.swing.JLabel();
        idCustomerTextField = new javax.swing.JTextField();
        namaCustomerPanel = new javax.swing.JPanel();
        namaCustomerLabel = new javax.swing.JLabel();
        namaCustomerTextField = new javax.swing.JTextField();
        noTeleponPanel = new javax.swing.JPanel();
        noTeleponLabel = new javax.swing.JLabel();
        noTeleponTextField = new javax.swing.JTextField();
        noTeleponPanel1 = new javax.swing.JPanel();
        noTeleponLabel1 = new javax.swing.JLabel();
        noTeleponTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        card4Text10 = new javax.swing.JLabel();
        card4 = new javax.swing.JPanel();
        card4Text2 = new javax.swing.JLabel();
        card4Text3 = new javax.swing.JLabel();
        card4Text1 = new javax.swing.JLabel();
        gambarCard4 = new javax.swing.JLabel();
        card5 = new javax.swing.JPanel();
        card4Text4 = new javax.swing.JLabel();
        card4Text5 = new javax.swing.JLabel();
        card4Text6 = new javax.swing.JLabel();
        gambarCard5 = new javax.swing.JLabel();
        card6 = new javax.swing.JPanel();
        card4Text7 = new javax.swing.JLabel();
        card4Text8 = new javax.swing.JLabel();
        card4Text9 = new javax.swing.JLabel();
        gambarCard6 = new javax.swing.JLabel();
        customerScrollPane = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        formCustomerLabel1 = new javax.swing.JLabel();
        simpanCustomerButton = new javax.swing.JButton();
        batalCustomerButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1356, 644));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1356, 644));

        customerManagementPanel.setBackground(new java.awt.Color(190, 205, 238));
        customerManagementPanel.setPreferredSize(new java.awt.Dimension(1356, 99));

        customerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penjualanManagement.png"))); // NOI18N

        customerManagementLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        customerManagementLabel.setText("PENJUALAN MANAGEMENT");

        customerManagementLabel2.setBackground(new java.awt.Color(0, 0, 0));
        customerManagementLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerManagementLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerManagementLabel2.setText("Kelola Transaksi Penjualan PetShop dengan Mudah");

        javax.swing.GroupLayout customerManagementPanelLayout = new javax.swing.GroupLayout(customerManagementPanel);
        customerManagementPanel.setLayout(customerManagementPanelLayout);
        customerManagementPanelLayout.setHorizontalGroup(
            customerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerManagementPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(customerIconLabel)
                .addGap(18, 18, 18)
                .addGroup(customerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerManagementPanelLayout.createSequentialGroup()
                        .addComponent(customerManagementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1116, 1116, 1116))
                    .addGroup(customerManagementPanelLayout.createSequentialGroup()
                        .addComponent(customerManagementLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        customerManagementPanelLayout.setVerticalGroup(
            customerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerManagementPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(customerManagementLabel)
                .addGap(0, 0, 0)
                .addComponent(customerManagementLabel2)
                .addGap(25, 25, 25))
            .addComponent(customerIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        searchCustomerInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchCustomerInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchCustomerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N

        searchCustomerInputTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        searchCustomerInputTextField.setText("Cari Penjualan . . .");
        searchCustomerInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerInputTextFieldActionPerformed(evt);
            }
        });
        searchCustomerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchCustomerInputTextFieldKeyPressed(evt);
            }
        });

        searchCustomerInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchCustomerInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerInputButton.setText("Cari");
        searchCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerInputPanelLayout = new javax.swing.GroupLayout(searchCustomerInputPanel);
        searchCustomerInputPanel.setLayout(searchCustomerInputPanelLayout);
        searchCustomerInputPanelLayout.setHorizontalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchCustomerInputPanelLayout.setVerticalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchCustomerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        customerFormPanel.setBackground(new java.awt.Color(238, 242, 250));

        formCustomerLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        formCustomerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/formCustomer.png"))); // NOI18N
        formCustomerLabel.setText("DATA PENJUALAN");

        customerButtonPanel.setBackground(new java.awt.Color(238, 242, 250));

        barukanCustomerButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanCustomerButton.setText("Barukan");
        barukanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanCustomerButtonActionPerformed(evt);
            }
        });

        hapusCustomerButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusCustomerButton.setText("Hapus");
        hapusCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusCustomerButtonActionPerformed(evt);
            }
        });

        tambahCustomerButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahCustomerButton.setText("Tambah");
        tambahCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerButtonPanelLayout = new javax.swing.GroupLayout(customerButtonPanel);
        customerButtonPanel.setLayout(customerButtonPanelLayout);
        customerButtonPanelLayout.setHorizontalGroup(
            customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(barukanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        customerButtonPanelLayout.setVerticalGroup(
            customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        idCustomerPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idCustomerLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idCustomerLabel.setText("ID Customer");

        idCustomerTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idCustomerPanelLayout = new javax.swing.GroupLayout(idCustomerPanel);
        idCustomerPanel.setLayout(idCustomerPanelLayout);
        idCustomerPanelLayout.setHorizontalGroup(
            idCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idCustomerPanelLayout.createSequentialGroup()
                        .addComponent(idCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(idCustomerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        idCustomerPanelLayout.setVerticalGroup(
            idCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idCustomerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaCustomerPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaCustomerLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaCustomerLabel.setText("Nama Customer");

        namaCustomerTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout namaCustomerPanelLayout = new javax.swing.GroupLayout(namaCustomerPanel);
        namaCustomerPanel.setLayout(namaCustomerPanelLayout);
        namaCustomerPanelLayout.setHorizontalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                        .addComponent(namaCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(namaCustomerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaCustomerPanelLayout.setVerticalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaCustomerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponPanel.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        noTeleponLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noTeleponLabel.setText("No Telepon");

        noTeleponTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout noTeleponPanelLayout = new javax.swing.GroupLayout(noTeleponPanel);
        noTeleponPanel.setLayout(noTeleponPanelLayout);
        noTeleponPanelLayout.setHorizontalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noTeleponPanelLayout.createSequentialGroup()
                        .addComponent(noTeleponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        noTeleponPanelLayout.setVerticalGroup(
            noTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponPanel1.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponPanel1.setPreferredSize(new java.awt.Dimension(322, 60));

        noTeleponLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noTeleponLabel1.setText("No Telepon");

        noTeleponTextField1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        noTeleponTextField1.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout noTeleponPanel1Layout = new javax.swing.GroupLayout(noTeleponPanel1);
        noTeleponPanel1.setLayout(noTeleponPanel1Layout);
        noTeleponPanel1Layout.setHorizontalGroup(
            noTeleponPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noTeleponPanel1Layout.createSequentialGroup()
                        .addComponent(noTeleponLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(noTeleponTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        noTeleponPanel1Layout.setVerticalGroup(
            noTeleponPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noTeleponPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout customerFormPanelLayout = new javax.swing.GroupLayout(customerFormPanel);
        customerFormPanel.setLayout(customerFormPanelLayout);
        customerFormPanelLayout.setHorizontalGroup(
            customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addComponent(customerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerFormPanelLayout.createSequentialGroup()
                                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noTeleponPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(formCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        customerFormPanelLayout.setVerticalGroup(
            customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addComponent(formCustomerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(noTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTeleponPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(customerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(238, 242, 250));

        jPanel2.setBackground(new java.awt.Color(238, 242, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penjualan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        card4Text10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        card4Text10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card4Text10.setText("Total Penjualan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card4Text10, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(card4Text10)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        card4.setBackground(new java.awt.Color(255, 255, 255));
        card4.setPreferredSize(new java.awt.Dimension(687, 65));

        card4Text2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        card4Text2.setText("0");

        card4Text3.setText("Janji Temu");

        card4Text1.setText("Grooming Hari Ini");

        gambarCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/schedule.png"))); // NOI18N

        javax.swing.GroupLayout card4Layout = new javax.swing.GroupLayout(card4);
        card4.setLayout(card4Layout);
        card4Layout.setHorizontalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarCard4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(card4Text1)
                    .addComponent(card4Text2)
                    .addComponent(card4Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        card4Layout.setVerticalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card4Layout.createSequentialGroup()
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(card4Layout.createSequentialGroup()
                        .addComponent(card4Text1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card4Text2)
                        .addGap(2, 2, 2)
                        .addComponent(card4Text3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(card4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gambarCard4)))
                .addGap(20, 20, 20))
        );

        card5.setBackground(new java.awt.Color(255, 255, 255));
        card5.setPreferredSize(new java.awt.Dimension(687, 65));

        card4Text4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        card4Text4.setText("0");

        card4Text5.setText("Janji Temu");

        card4Text6.setText("Grooming Hari Ini");

        gambarCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/schedule.png"))); // NOI18N

        javax.swing.GroupLayout card5Layout = new javax.swing.GroupLayout(card5);
        card5.setLayout(card5Layout);
        card5Layout.setHorizontalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarCard5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(card4Text6)
                    .addComponent(card4Text4)
                    .addComponent(card4Text5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        card5Layout.setVerticalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card5Layout.createSequentialGroup()
                .addGroup(card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(card5Layout.createSequentialGroup()
                        .addComponent(card4Text6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card4Text4)
                        .addGap(2, 2, 2)
                        .addComponent(card4Text5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(card5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gambarCard5)))
                .addGap(20, 20, 20))
        );

        card6.setBackground(new java.awt.Color(255, 255, 255));
        card6.setPreferredSize(new java.awt.Dimension(687, 65));

        card4Text7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        card4Text7.setText("0");

        card4Text8.setText("Janji Temu");

        card4Text9.setText("Grooming Hari Ini");

        gambarCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/schedule.png"))); // NOI18N

        javax.swing.GroupLayout card6Layout = new javax.swing.GroupLayout(card6);
        card6.setLayout(card6Layout);
        card6Layout.setHorizontalGroup(
            card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarCard6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(card4Text9)
                    .addComponent(card4Text7)
                    .addComponent(card4Text8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        card6Layout.setVerticalGroup(
            card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card6Layout.createSequentialGroup()
                .addGroup(card6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(card6Layout.createSequentialGroup()
                        .addComponent(card4Text9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card4Text7)
                        .addGap(2, 2, 2)
                        .addComponent(card4Text8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(card6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gambarCard6)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(card6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        customerScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomerMouseClicked(evt);
            }
        });
        customerScrollPane.setViewportView(tableCustomer);

        formCustomerLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        formCustomerLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/formCustomer.png"))); // NOI18N
        formCustomerLabel1.setText("DATA TRANSAKSI PENJUALAN");

        simpanCustomerButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanCustomerButton.setText("Simpan");
        simpanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanCustomerButtonActionPerformed(evt);
            }
        });

        batalCustomerButton.setBackground(new java.awt.Color(237, 8, 0));
        batalCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        batalCustomerButton.setText("Batalkan");
        batalCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1558, Short.MAX_VALUE)
            .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1558, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(customerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formCustomerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(batalCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(customerManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(batalCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formCustomerLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustomerInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchCustomerInputTextFieldKeyPressed

    private void searchCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerInputButtonActionPerformed
       
    }//GEN-LAST:event_searchCustomerInputButtonActionPerformed

    private void barukanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanCustomerButtonActionPerformed
        
    }//GEN-LAST:event_barukanCustomerButtonActionPerformed

    private void hapusCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusCustomerButtonActionPerformed
        
    }//GEN-LAST:event_hapusCustomerButtonActionPerformed

    private void tambahCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahCustomerButtonActionPerformed
        
    }//GEN-LAST:event_tambahCustomerButtonActionPerformed

    private void simpanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanCustomerButtonActionPerformed
        
    }//GEN-LAST:event_simpanCustomerButtonActionPerformed

    private void searchCustomerInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerInputTextFieldActionPerformed

    private void batalCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalCustomerButtonActionPerformed
        
    }//GEN-LAST:event_batalCustomerButtonActionPerformed

    private void tableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseClicked
        
    }//GEN-LAST:event_tableCustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanCustomerButton;
    private javax.swing.JButton batalCustomerButton;
    private javax.swing.JPanel card4;
    private javax.swing.JLabel card4Text1;
    private javax.swing.JLabel card4Text10;
    private javax.swing.JLabel card4Text2;
    private javax.swing.JLabel card4Text3;
    private javax.swing.JLabel card4Text4;
    private javax.swing.JLabel card4Text5;
    private javax.swing.JLabel card4Text6;
    private javax.swing.JLabel card4Text7;
    private javax.swing.JLabel card4Text8;
    private javax.swing.JLabel card4Text9;
    private javax.swing.JPanel card5;
    private javax.swing.JPanel card6;
    private javax.swing.JPanel customerButtonPanel;
    private javax.swing.JPanel customerFormPanel;
    private javax.swing.JLabel customerIconLabel;
    private javax.swing.JLabel customerManagementLabel;
    private javax.swing.JLabel customerManagementLabel2;
    private javax.swing.JPanel customerManagementPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JLabel formCustomerLabel;
    private javax.swing.JLabel formCustomerLabel1;
    private javax.swing.JLabel gambarCard4;
    private javax.swing.JLabel gambarCard5;
    private javax.swing.JLabel gambarCard6;
    private javax.swing.JButton hapusCustomerButton;
    private javax.swing.JLabel idCustomerLabel;
    private javax.swing.JPanel idCustomerPanel;
    private javax.swing.JTextField idCustomerTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaCustomerLabel;
    private javax.swing.JPanel namaCustomerPanel;
    private javax.swing.JTextField namaCustomerTextField;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JLabel noTeleponLabel1;
    private javax.swing.JPanel noTeleponPanel;
    private javax.swing.JPanel noTeleponPanel1;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JTextField noTeleponTextField1;
    private javax.swing.JLabel searchCustomerIconLabel;
    private javax.swing.JButton searchCustomerInputButton;
    private javax.swing.JPanel searchCustomerInputPanel;
    private javax.swing.JTextField searchCustomerInputTextField;
    private javax.swing.JButton simpanCustomerButton;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JButton tambahCustomerButton;
    // End of variables declaration//GEN-END:variables
}
