package panelView;

public class ProdukMainPanel extends javax.swing.JPanel {
    

    public ProdukMainPanel() {
        initComponents();
        setOpaque(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        produkLabel = new javax.swing.JLabel();
        searchProdukInputPanel = new javax.swing.JPanel();
        searchProdukInputLabel = new javax.swing.JLabel();
        searchProdukInputTextField = new javax.swing.JTextField();
        searchProdukInputButton = new javax.swing.JButton();
        produkFormPanel = new javax.swing.JPanel();
        produkButtonPanel = new javax.swing.JPanel();
        barukanProdukButton = new javax.swing.JButton();
        hapusProdukButton = new javax.swing.JButton();
        tambahProdukButton = new javax.swing.JButton();
        idProdukPanel = new javax.swing.JPanel();
        idProdukLabel = new javax.swing.JLabel();
        idProdukTextField = new javax.swing.JTextField();
        namaProdukPanel = new javax.swing.JPanel();
        namaProdukLabel = new javax.swing.JLabel();
        namaProdukTextField = new javax.swing.JTextField();
        kategoriProdukPanel = new javax.swing.JPanel();
        kategoriProdukLabel = new javax.swing.JLabel();
        kategoriProdukDropdown = new javax.swing.JComboBox<>();
        hargaProdukPanel = new javax.swing.JPanel();
        hargaProdukLabel = new javax.swing.JLabel();
        hargaProdukTextField = new javax.swing.JTextField();
        stokProdukPanel = new javax.swing.JPanel();
        stokProdukLabel = new javax.swing.JLabel();
        stokProdukTextField = new javax.swing.JTextField();
        deskripsiProdukPanel = new javax.swing.JPanel();
        deskripsiProdukLabel = new javax.swing.JLabel();
        deskripsiProdukScrollPane = new javax.swing.JScrollPane();
        deskripsiProdukTextArea = new javax.swing.JTextArea();
        simpanProdukButton = new javax.swing.JButton();
        batalProdukButton = new javax.swing.JButton();
        produkScrollPane = new javax.swing.JScrollPane();
        tableProduk = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        produkLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        produkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produkLabel.setText("PRODUK");

        searchProdukInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchProdukInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchProdukInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchProdukInputLabel.setText("Pencarian Produk");

        searchProdukInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchProdukInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProdukInputTextFieldActionPerformed(evt);
            }
        });
        searchProdukInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchProdukInputTextFieldKeyPressed(evt);
            }
        });

        searchProdukInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchProdukInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchProdukInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchProdukInputButton.setText("Cari");
        searchProdukInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProdukInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchProdukInputPanelLayout = new javax.swing.GroupLayout(searchProdukInputPanel);
        searchProdukInputPanel.setLayout(searchProdukInputPanelLayout);
        searchProdukInputPanelLayout.setHorizontalGroup(
            searchProdukInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchProdukInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchProdukInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchProdukInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchProdukInputPanelLayout.createSequentialGroup()
                        .addComponent(searchProdukInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchProdukInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchProdukInputPanelLayout.setVerticalGroup(
            searchProdukInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchProdukInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchProdukInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchProdukInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchProdukInputTextField)
                    .addComponent(searchProdukInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        produkFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        produkButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanProdukButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanProdukButton.setText("Barukan");
        barukanProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanProdukButtonActionPerformed(evt);
            }
        });

        hapusProdukButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusProdukButton.setText("Hapus");
        hapusProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusProdukButtonActionPerformed(evt);
            }
        });

        tambahProdukButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahProdukButton.setText("Tambah");
        tambahProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahProdukButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout produkButtonPanelLayout = new javax.swing.GroupLayout(produkButtonPanel);
        produkButtonPanel.setLayout(produkButtonPanelLayout);
        produkButtonPanelLayout.setHorizontalGroup(
            produkButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahProdukButton)
                .addGap(18, 18, 18)
                .addComponent(barukanProdukButton)
                .addGap(18, 18, 18)
                .addComponent(hapusProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        produkButtonPanelLayout.setVerticalGroup(
            produkButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produkButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahProdukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusProdukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        idProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        idProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idProdukLabel.setText("ID Produk");

        idProdukTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout idProdukPanelLayout = new javax.swing.GroupLayout(idProdukPanel);
        idProdukPanel.setLayout(idProdukPanelLayout);
        idProdukPanelLayout.setHorizontalGroup(
            idProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idProdukPanelLayout.createSequentialGroup()
                        .addComponent(idProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(idProdukTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        idProdukPanelLayout.setVerticalGroup(
            idProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idProdukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        namaProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaProdukLabel.setText("Nama Produk");

        namaProdukTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaProdukTextField.setPreferredSize(new java.awt.Dimension(72, 21));

        javax.swing.GroupLayout namaProdukPanelLayout = new javax.swing.GroupLayout(namaProdukPanel);
        namaProdukPanel.setLayout(namaProdukPanelLayout);
        namaProdukPanelLayout.setHorizontalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaProdukPanelLayout.createSequentialGroup()
                        .addComponent(namaProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(namaProdukTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaProdukPanelLayout.setVerticalGroup(
            namaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaProdukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kategoriProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        kategoriProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        kategoriProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kategoriProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kategoriProdukLabel.setText("Kategori Produk");

        kategoriProdukDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kategoriProdukDropdown.setPreferredSize(new java.awt.Dimension(72, 21));
        kategoriProdukDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriProdukDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kategoriProdukPanelLayout = new javax.swing.GroupLayout(kategoriProdukPanel);
        kategoriProdukPanel.setLayout(kategoriProdukPanelLayout);
        kategoriProdukPanelLayout.setHorizontalGroup(
            kategoriProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kategoriProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kategoriProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kategoriProdukPanelLayout.createSequentialGroup()
                        .addComponent(kategoriProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(kategoriProdukDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kategoriProdukPanelLayout.setVerticalGroup(
            kategoriProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kategoriProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoriProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategoriProdukDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        hargaProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        hargaProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hargaProdukLabel.setText("Harga Produk");

        hargaProdukTextField.setPreferredSize(new java.awt.Dimension(72, 21));
        hargaProdukTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaProdukTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hargaProdukPanelLayout = new javax.swing.GroupLayout(hargaProdukPanel);
        hargaProdukPanel.setLayout(hargaProdukPanelLayout);
        hargaProdukPanelLayout.setHorizontalGroup(
            hargaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hargaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hargaProdukPanelLayout.createSequentialGroup()
                        .addComponent(hargaProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(hargaProdukTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        hargaProdukPanelLayout.setVerticalGroup(
            hargaProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hargaProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hargaProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hargaProdukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        stokProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        stokProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        stokProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        stokProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stokProdukLabel.setText("Stok Produk");

        stokProdukTextField.setPreferredSize(new java.awt.Dimension(72, 21));
        stokProdukTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokProdukTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stokProdukPanelLayout = new javax.swing.GroupLayout(stokProdukPanel);
        stokProdukPanel.setLayout(stokProdukPanelLayout);
        stokProdukPanelLayout.setHorizontalGroup(
            stokProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stokProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stokProdukPanelLayout.createSequentialGroup()
                        .addComponent(stokProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(stokProdukTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        stokProdukPanelLayout.setVerticalGroup(
            stokProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stokProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stokProdukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deskripsiProdukPanel.setBackground(new java.awt.Color(255, 255, 255));
        deskripsiProdukPanel.setPreferredSize(new java.awt.Dimension(322, 60));

        deskripsiProdukLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        deskripsiProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deskripsiProdukLabel.setText("Deskripsi Produk");

        deskripsiProdukTextArea.setColumns(20);
        deskripsiProdukTextArea.setRows(5);
        deskripsiProdukScrollPane.setViewportView(deskripsiProdukTextArea);

        javax.swing.GroupLayout deskripsiProdukPanelLayout = new javax.swing.GroupLayout(deskripsiProdukPanel);
        deskripsiProdukPanel.setLayout(deskripsiProdukPanelLayout);
        deskripsiProdukPanelLayout.setHorizontalGroup(
            deskripsiProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskripsiProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskripsiProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskripsiProdukPanelLayout.createSequentialGroup()
                        .addComponent(deskripsiProdukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(deskripsiProdukScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );
        deskripsiProdukPanelLayout.setVerticalGroup(
            deskripsiProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskripsiProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deskripsiProdukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskripsiProdukScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout produkFormPanelLayout = new javax.swing.GroupLayout(produkFormPanel);
        produkFormPanel.setLayout(produkFormPanelLayout);
        produkFormPanelLayout.setHorizontalGroup(
            produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produkFormPanelLayout.createSequentialGroup()
                        .addComponent(produkButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(produkFormPanelLayout.createSequentialGroup()
                        .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategoriProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(deskripsiProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 236, Short.MAX_VALUE))))
        );
        produkFormPanelLayout.setVerticalGroup(
            produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produkButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produkFormPanelLayout.createSequentialGroup()
                        .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(produkFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stokProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(produkFormPanelLayout.createSequentialGroup()
                                .addComponent(namaProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kategoriProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(deskripsiProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanProdukButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanProdukButton.setText("Simpan");
        simpanProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanProdukButtonActionPerformed(evt);
            }
        });

        batalProdukButton.setBackground(new java.awt.Color(237, 8, 0));
        batalProdukButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        batalProdukButton.setText("Batalkan");
        batalProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalProdukButtonActionPerformed(evt);
            }
        });

        produkScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdukMouseClicked(evt);
            }
        });
        produkScrollPane.setViewportView(tableProduk);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchProdukInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                    .addComponent(produkScrollPane)
                    .addComponent(produkFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batalProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(produkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(produkLabel)
                .addGap(18, 18, 18)
                .addComponent(searchProdukInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(produkFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(produkScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchProdukInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProdukInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchProdukInputTextFieldKeyPressed

    private void searchProdukInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProdukInputButtonActionPerformed
       
    }//GEN-LAST:event_searchProdukInputButtonActionPerformed

    private void barukanProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanProdukButtonActionPerformed
        
    }//GEN-LAST:event_barukanProdukButtonActionPerformed

    private void hapusProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusProdukButtonActionPerformed
        
    }//GEN-LAST:event_hapusProdukButtonActionPerformed

    private void tambahProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahProdukButtonActionPerformed
        
    }//GEN-LAST:event_tambahProdukButtonActionPerformed

    private void simpanProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanProdukButtonActionPerformed
        
    }//GEN-LAST:event_simpanProdukButtonActionPerformed

    private void searchProdukInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProdukInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProdukInputTextFieldActionPerformed

    private void kategoriProdukDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriProdukDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriProdukDropdownActionPerformed

    private void batalProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalProdukButtonActionPerformed
        
    }//GEN-LAST:event_batalProdukButtonActionPerformed

    private void tableProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdukMouseClicked
        
    }//GEN-LAST:event_tableProdukMouseClicked

    private void hargaProdukTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaProdukTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaProdukTextFieldActionPerformed

    private void stokProdukTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokProdukTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokProdukTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanProdukButton;
    private javax.swing.JButton batalProdukButton;
    private javax.swing.JLabel deskripsiProdukLabel;
    private javax.swing.JPanel deskripsiProdukPanel;
    private javax.swing.JScrollPane deskripsiProdukScrollPane;
    private javax.swing.JTextArea deskripsiProdukTextArea;
    private javax.swing.JButton hapusProdukButton;
    private javax.swing.JLabel hargaProdukLabel;
    private javax.swing.JPanel hargaProdukPanel;
    private javax.swing.JTextField hargaProdukTextField;
    private javax.swing.JLabel idProdukLabel;
    private javax.swing.JPanel idProdukPanel;
    private javax.swing.JTextField idProdukTextField;
    private javax.swing.JComboBox<KendaraanE> kategoriProdukDropdown;
    private javax.swing.JLabel kategoriProdukLabel;
    private javax.swing.JPanel kategoriProdukPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaProdukLabel;
    private javax.swing.JPanel namaProdukPanel;
    private javax.swing.JTextField namaProdukTextField;
    private javax.swing.JPanel produkButtonPanel;
    private javax.swing.JPanel produkFormPanel;
    private javax.swing.JLabel produkLabel;
    private javax.swing.JScrollPane produkScrollPane;
    private javax.swing.JButton searchProdukInputButton;
    private javax.swing.JLabel searchProdukInputLabel;
    private javax.swing.JPanel searchProdukInputPanel;
    private javax.swing.JTextField searchProdukInputTextField;
    private javax.swing.JButton simpanProdukButton;
    private javax.swing.JLabel stokProdukLabel;
    private javax.swing.JPanel stokProdukPanel;
    private javax.swing.JTextField stokProdukTextField;
    private javax.swing.JTable tableProduk;
    private javax.swing.JButton tambahProdukButton;
    // End of variables declaration//GEN-END:variables
}
